#!/bin/bash

# Make script strict
# e: exit on error
# u: error on undefined variables
# o pipefail: failed command in | counts as failure
set -euo pipefail

# === FLAGS ===
DRY_RUN=false
INSTALL_YAY=false

for arg in "$@"; do
	case $arg in
		-d|--dry-run)	DRY_RUN=true ;;
		--yay)			INSTALL_YAY=true ;;
		*)				echo "Unknown argument: $arg"; exit 1 ;;
	esac
done

# === PATHS ===
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PACMAN_LIST="$REPO_DIR/packages/pacman.txt"
AUR_LIST="$REPO_DIR/packages/aur.txt"

# === LOAD HELPERS ===
source "$SCRIPT_DIR/lib/methods.sh"

setup_symlinks () {
	if $DRY_RUN; then 
		"$SCRIPT_DIR/setup_symlinks" -d
		return
	fi

	"$SCRIPT_DIR/setup_symlinks"
}


# === MAIN ===
install_yay 
install_pacman
install_aur 
setup_symlinks
